### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by shinegod** [foggyspace/NsePocsuite-lua#1]
NSE: Updating rule database.
NSE: Failed to load /usr/bin/../share/nmap/scripts//cnvd-2021-14544.nse:
/usr/bin/../share/nmap/scripts//cnvd-2021-14544.nse:19: attempt to index a nil value (local 'shortport')
stack traceback:
        /usr/bin/../share/nmap/scripts//cnvd-2021-14544.nse:19: in function </usr/bin/../share/nmap/scripts//cnvd-2021-14544.nse:1>
NSE: failed to initialize the script engine:
/usr/bin/../share/nmap/nse_main.lua:614: could not load script
stack traceback:
        [C]: in function 'error'
        /usr/bin/../share/nmap/nse_main.lua:614: in field 'new'
        /usr/bin/../share/nmap/nse_main.lua:1296: in main chunk
        [C]: in ?

QUITTING!

**Comment by seaung** [comment]
谢谢你，我在我本地机器上修改了脚本，并做了调试已经没什么问题了，以下是我在我本地的测试结果
命令如下所示
nmap --script=./cnvd-2021-14544.nse -p 80 ip_address

Nmap scan report for li1249-80.members.linode.com (x.x.x.x)
Host is up (0.38s latency).

PORT   STATE SERVICE
80/tcp open  http
|_cnvd-2021-14544: [-] Not Found vulnerable

Nmap done: 1 IP address (1 host up) scanned in 3.65 seconds

**Comment by shinegod** [comment]
> 谢谢你，我在我本地机器上修改了脚本，并做了调试已经没什么问题了，以下是我在我本地的测试结果
> 命令如下所示
> nmap --script=./cnvd-2021-14544.nse -p 80 ip_address
> 
> Nmap scan report for li1249-80.members.linode.com (x.x.x.x)
> Host is up (0.38s latency).
> 
> PORT STATE SERVICE
> 80/tcp open http
> |_cnvd-2021-14544: [-] Not Found vulnerable
> 
> Nmap done: 1 IP address (1 host up) scanned in 3.65 seconds

老哥，其他的nse 也报错， - -我忘记说了。

**Comment by seaung** [comment]
谢啦老弟，我有空改一下吧
